package client_application;
/**
 * @author Sarp Cagin Erdogan
 */
public enum TaskType {
    FAILEDSOCKET,
    GOTID,
    CHATMESSAGE,
    FIGURETAKEN,
    LAUNCHLOBBY,
    UPDATEREADYBUTTON,
    UPDATELOBBYLIST,
    AVAILABLEMAPS,
    TRIGGERSTART,
    TRIGGERFINISH,
    UPDATEGAMEBOARD,
    UPDATE_PROGCARDS,
    UPDATE_HANDCARDS,
    UPDATEOTHERSREGISTERS,
    STARTING_POINT_NOT_AVAILABLE,
    STARTING_POINT_INVALID,
    CHOOSE_STARTING_POINT,
    WIN,
    LOSE,
    REBOOTDIRECTION,

    ERROR;
}
