package client_application;
/**
 * @author Sarp Cagin Erdogan
 */
public enum TaskType {
    FAILEDSOCKET,
    GOTID,
    CHATMESSAGE,
    FIGURETAKEN,
    LAUNCHLOBBY,
    UPDATEREADYBUTTON,
    UPDATELOBBYLIST,
    AVAILABLEMAPS,
    TRIGGERSTART,
    UPDATEGAMEBOARD,
    UPDATEOWNREGISTER,
    UPDATEAVAILABLEREGISTER,
    UPDATEOTHERSREGISTERS,

    ERROR;
}
